### ISSUE TITLE
Client files not autorefreshing on linux

### ISSUE THREAD

**Issue by Riddle1001** [Pika-Software/gm_moonloader#12]
Steps to reproduce:
1. Autorun file
```lua
AddCSLuaFile("test.lua")
include("test.lua")
```
2. Put a print statement inside `test.lua`
3. Change the print statement's contents inside `test.lua`
4. Save `test.lua`
5. The server correctly refreshes with the new print statement's contents
6. You will see the client does not

Tested on:
- Linux, Ubuntu 22.04
- Default garry's mode branch
- using `gmcl_moonloader_linux.dll`,  `gmsv_moonloader_linux.dll`

**Comment by dankmolot** [comment]
Are you using moonloader v1.3.0 or v2.0.0?

**Comment by Riddle1001** [comment]
> Are you using moonloader v1.3.0 or v2.0.0?

I do not remember, I believe moonloader v1.3.0. However, I just tested with v2.0.0 and the same result happens. The client does not receive the updated file.

**Comment by dankmolot** [comment]
Just to clarify. Are you creating `test.lua` or `test.yue`? If `test.lua` then it means that `moonloader` breaks Garry's Mod autorefresh, right?

**Comment by Riddle1001** [comment]
> Just to clarify. Are you creating `test.lua` or `test.yue`? If `test.lua` then it means that `moonloader` breaks Garry's Mod autorefresh, right?

I am creating test.yue. After retesting, I see it isn't refreshing on the server either now either..

I will clarify all steps, maybe i'm doing something wrong.

Addon directory:
```
~/new_server/garrysmod/addons/test_addon ❯ tree                                                                                                                12:17:51 PM
.
└── lua
    ├── autorun
    │   └── run.lua
    └── test.yue
 ```

lua/bin/
```
~/new_server/garrysmod/lua/bin ❯ tree                                                                                                                          12:18:21 PM
.
├── gmcl_moonloader_linux.dll
└── gmsv_moonloader_linux.dll
```

`test_addon/lua/autorun/run.lua` contents:
```lua
if SERVER then
    require "moonloader"
    AddCSLuaFile("test.lua")
end

include("test.lua")
```

`test_addon/lua/test.yue` contents:
```lua
print "Hello from Moonscript! ##{i}" for i = 1, 5
```

It does print
```
Hello from Moonscript! #1
Hello from Moonscript! #2
..
```

However, after I change the contents of `test_addon/lua/test.yue` to
```lua
print "Bye!!!!!! from Moonscript! ##{i}" for i = 1, 5 
```

and then save `test_addon/lua/test.yue`, then save `test_addon/lua/autorun/run.lua` to trigger a refresh, it runs the previous code of `test.yue`, and not the new code.

**Comment by Riddle1001** [comment]
https://github.com/Pika-Software/gm_moonloader/assets/75004732/7007cb57-7f24-446c-bb88-1c1f020d0df1

**Comment by dankmolot** [comment]
I have made a VM with Ubuntu, will try to reproduce your issue.

**Comment by dankmolot** [comment]
Can you please download this dev binary and test again?

[gmsv_moonloader_linux.dll.zip](https://github.com/user-attachments/files/15931096/gmsv_moonloader_linux.dll.zip)

**Comment by Riddle1001** [comment]
> Can you please download this dev binary and test again?
> 
> [gmsv_moonloader_linux.dll.zip](https://github.com/user-attachments/files/15931096/gmsv_moonloader_linux.dll.zip)

It appears to still not being working for me. I see the `Trying to auto refresh file 'lua/test.lua'` but it doesn't work still.

**Comment by Riddle1001** [comment]
From my understanding, it seems that `lua/test.lua` isn't being recompiled

**Comment by dankmolot** [comment]
Since you saw message about trying to auto refresh, Moonloader must have catched that you changed the file, recompiled it if last file modified date has changed, and sent to Garry's Mod a signal to autorefresh it. 

I have tested on my side, it refresh the file. 

Currently have no clue what the issue might be something related to filesystem and update date.

**Comment by dankmolot** [comment]
I'll add more debug messages, let's see what is on your side

**Comment by dankmolot** [comment]
[gmsv_moonloader_linux.dll.zip](https://github.com/user-attachments/files/15931625/gmsv_moonloader_linux.dll.zip)

Now I see that `NeedsCompile=0`, that means that moonloader detects like file haven't changed at all, and decides not to recompile it. Can you send if it is the same on your side?

**Comment by Riddle1001** [comment]
> [gmsv_moonloader_linux.dll.zip](https://github.com/user-attachments/files/15931625/gmsv_moonloader_linux.dll.zip)
> 
> Now I see that `NeedsCompile=0`, that means that moonloader detects like file haven't changed at all, and decides not to recompile it. Can you send if it is the same on your side?


https://github.com/Pika-Software/gm_moonloader/assets/75004732/db676cf9-7a13-44e3-889c-ba878b4fc0ef

**Comment by dankmolot** [comment]
Well, you have found an interesting bug! If you will create a `.yue` file at the root of `lua/`, compiler will create a folder with the same name and `GetFileTime` will return a last edit time **of created folder**, not of `.yue` file. Easy fix, just need to change the `RemoveFilename` function

**Comment by dankmolot** [comment]
https://github.com/Pika-Software/gm_moonloader/actions/runs/9618898147

If everything runs fine on your side, I'll push it to main branch

**Comment by Riddle1001** [comment]
> Well, you have found an interesting bug! If you will create a `.yue` file at the root of `lua/`, compiler will create a folder with the same name and `GetFileTime` will return a last edit time **of created folder**, not of `.yue` file. Easy fix, just need to change the `RemoveFilename` function

Interesting, glad it's been found :D

> https://github.com/Pika-Software/gm_moonloader/actions/runs/9618898147
> 
> If everything runs fine on your side, I'll push it to main branch

I tested it on client and server, both seem to be working properly and refreshing. Thanks!

P.S `Trying to auto refresh file 'lua/test.lua'` is being printed still

**Comment by dankmolot** [comment]
Unfortunately currently Linux build is relaying on `lua_refresh_file` command since native autorefresh for some reason don't work. And I can't hide `Trying to auto refresh file 'lua/test.lua'` message :(

Also I see that during initial load for some reason file is being loaded two times. Tommorow will investigate why and how to fix it. Probably some Garry's Mod shenanigans

**Comment by dankmolot** [comment]
@Riddle1001, I completely fixed autorefresh issues on Linux, try out [latest release](https://github.com/Pika-Software/gm_moonloader/releases/tag/2.1.0)!
